---
- hosts: localhost
  tasks:
    - name: Creating resource group - "{{resourcegroupname}}"
      azure_rm_resourcegroup:
        name: "{{resourcegroupname}}"
        location: "eastasia"
      register: rg
    - debug:
        var: rg
