---
- hosts: localhost
  tasks:
    - name: Verify resource group
      azure_rm_resourcegroup_info:
        name: "{{resourcegroupname}}"
      register: rg
    - debug:
        var: rg.resourcegroups
  vars:
    resourcegroupname: ansible-hackathon-workflow
